export type AccountingZone = 'FRANCE' | 'OHADA' | 'IFRS'

export interface CountryConfig {
  code: string
  name: string
  flag: string
  currency: string
  currencySymbol: string
  currencyCode: string
  accountingZone: AccountingZone
  accountingPlan: string
  accountingNorms: string
  vatRates: number[]
  locale: string
  timezone: string
}

export interface CountryListItem {
  code: string
  name: string
  flag: string
}

export const PAYS_OHADA: readonly string[] = [
  'BJ', 'BF', 'CM', 'CF', 'KM', 'CG', 'CI',
  'GA', 'GN', 'GW', 'GQ', 'ML', 'NE', 'CD', 'SN', 'TD', 'TG',
]

export function getFlagEmoji(code: string): string {
  return [...code.toUpperCase()]
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join('')
}

// ── Internal data ─────────────────────────────────────────────────────────────

type CurrencyEntry = { code: string; symbol: string; locale: string }

const CURRENCY_DATA: Record<string, CurrencyEntry> = {
  AD: { code: 'EUR', symbol: '€',      locale: 'ca-AD' },
  AE: { code: 'AED', symbol: 'د.إ',   locale: 'ar-AE' },
  AF: { code: 'AFN', symbol: '؋',      locale: 'fa-AF' },
  AL: { code: 'ALL', symbol: 'L',      locale: 'sq-AL' },
  AM: { code: 'AMD', symbol: '֏',      locale: 'hy-AM' },
  AO: { code: 'AOA', symbol: 'Kz',     locale: 'pt-AO' },
  AR: { code: 'ARS', symbol: '$',      locale: 'es-AR' },
  AT: { code: 'EUR', symbol: '€',      locale: 'de-AT' },
  AU: { code: 'AUD', symbol: '$',      locale: 'en-AU' },
  AZ: { code: 'AZN', symbol: '₼',      locale: 'az-AZ' },
  BA: { code: 'BAM', symbol: 'KM',     locale: 'bs-BA' },
  BB: { code: 'BBD', symbol: '$',      locale: 'en-BB' },
  BD: { code: 'BDT', symbol: '৳',      locale: 'bn-BD' },
  BE: { code: 'EUR', symbol: '€',      locale: 'fr-BE' },
  BF: { code: 'XOF', symbol: 'F CFA',  locale: 'fr-BF' },
  BG: { code: 'BGN', symbol: 'лв',     locale: 'bg-BG' },
  BH: { code: 'BHD', symbol: '.د.ب',  locale: 'ar-BH' },
  BI: { code: 'BIF', symbol: 'Fr',     locale: 'fr-BI' },
  BJ: { code: 'XOF', symbol: 'F CFA',  locale: 'fr-BJ' },
  BN: { code: 'BND', symbol: '$',      locale: 'ms-BN' },
  BO: { code: 'BOB', symbol: 'Bs.',    locale: 'es-BO' },
  BR: { code: 'BRL', symbol: 'R$',     locale: 'pt-BR' },
  BS: { code: 'BSD', symbol: '$',      locale: 'en-BS' },
  BT: { code: 'BTN', symbol: 'Nu',     locale: 'dz-BT' },
  BW: { code: 'BWP', symbol: 'P',      locale: 'en-BW' },
  BY: { code: 'BYN', symbol: 'Br',     locale: 'be-BY' },
  BZ: { code: 'BZD', symbol: '$',      locale: 'en-BZ' },
  CA: { code: 'CAD', symbol: '$',      locale: 'en-CA' },
  CD: { code: 'CDF', symbol: 'FC',     locale: 'fr-CD' },
  CF: { code: 'XAF', symbol: 'F CFA',  locale: 'fr-CF' },
  CG: { code: 'XAF', symbol: 'F CFA',  locale: 'fr-CG' },
  CH: { code: 'CHF', symbol: 'Fr',     locale: 'fr-CH' },
  CI: { code: 'XOF', symbol: 'F CFA',  locale: 'fr-CI' },
  CL: { code: 'CLP', symbol: '$',      locale: 'es-CL' },
  CM: { code: 'XAF', symbol: 'F CFA',  locale: 'fr-CM' },
  CN: { code: 'CNY', symbol: '¥',      locale: 'zh-CN' },
  CO: { code: 'COP', symbol: '$',      locale: 'es-CO' },
  CR: { code: 'CRC', symbol: '₡',      locale: 'es-CR' },
  CU: { code: 'CUP', symbol: '$',      locale: 'es-CU' },
  CV: { code: 'CVE', symbol: '$',      locale: 'pt-CV' },
  CY: { code: 'EUR', symbol: '€',      locale: 'el-CY' },
  CZ: { code: 'CZK', symbol: 'Kč',    locale: 'cs-CZ' },
  DE: { code: 'EUR', symbol: '€',      locale: 'de-DE' },
  DJ: { code: 'DJF', symbol: 'Fr',     locale: 'fr-DJ' },
  DK: { code: 'DKK', symbol: 'kr',    locale: 'da-DK' },
  DO: { code: 'DOP', symbol: '$',      locale: 'es-DO' },
  DZ: { code: 'DZD', symbol: 'DA',    locale: 'fr-DZ' },
  EC: { code: 'USD', symbol: '$',      locale: 'es-EC' },
  EE: { code: 'EUR', symbol: '€',      locale: 'et-EE' },
  EG: { code: 'EGP', symbol: '£',      locale: 'ar-EG' },
  ES: { code: 'EUR', symbol: '€',      locale: 'es-ES' },
  ET: { code: 'ETB', symbol: 'Br',     locale: 'am-ET' },
  FI: { code: 'EUR', symbol: '€',      locale: 'fi-FI' },
  FJ: { code: 'FJD', symbol: '$',      locale: 'en-FJ' },
  FR: { code: 'EUR', symbol: '€',      locale: 'fr-FR' },
  GA: { code: 'XAF', symbol: 'F CFA',  locale: 'fr-GA' },
  GB: { code: 'GBP', symbol: '£',      locale: 'en-GB' },
  GE: { code: 'GEL', symbol: '₾',      locale: 'ka-GE' },
  GH: { code: 'GHS', symbol: '₵',      locale: 'en-GH' },
  GM: { code: 'GMD', symbol: 'D',      locale: 'en-GM' },
  GN: { code: 'GNF', symbol: 'FG',    locale: 'fr-GN' },
  GQ: { code: 'XAF', symbol: 'F CFA',  locale: 'fr-GQ' },
  GR: { code: 'EUR', symbol: '€',      locale: 'el-GR' },
  GT: { code: 'GTQ', symbol: 'Q',      locale: 'es-GT' },
  GW: { code: 'XOF', symbol: 'F CFA',  locale: 'pt-GW' },
  GY: { code: 'GYD', symbol: '$',      locale: 'en-GY' },
  HN: { code: 'HNL', symbol: 'L',      locale: 'es-HN' },
  HR: { code: 'EUR', symbol: '€',      locale: 'hr-HR' },
  HT: { code: 'HTG', symbol: 'G',      locale: 'fr-HT' },
  HU: { code: 'HUF', symbol: 'Ft',    locale: 'hu-HU' },
  ID: { code: 'IDR', symbol: 'Rp',    locale: 'id-ID' },
  IE: { code: 'EUR', symbol: '€',      locale: 'en-IE' },
  IL: { code: 'ILS', symbol: '₪',      locale: 'he-IL' },
  IN: { code: 'INR', symbol: '₹',      locale: 'hi-IN' },
  IQ: { code: 'IQD', symbol: 'ع.د',   locale: 'ar-IQ' },
  IR: { code: 'IRR', symbol: '﷼',      locale: 'fa-IR' },
  IS: { code: 'ISK', symbol: 'kr',    locale: 'is-IS' },
  IT: { code: 'EUR', symbol: '€',      locale: 'it-IT' },
  JM: { code: 'JMD', symbol: '$',      locale: 'en-JM' },
  JO: { code: 'JOD', symbol: 'د.ا',   locale: 'ar-JO' },
  JP: { code: 'JPY', symbol: '¥',      locale: 'ja-JP' },
  KE: { code: 'KES', symbol: 'Ksh',   locale: 'en-KE' },
  KG: { code: 'KGS', symbol: 'с',      locale: 'ky-KG' },
  KH: { code: 'KHR', symbol: '៛',      locale: 'km-KH' },
  KM: { code: 'KMF', symbol: 'FC',    locale: 'ar-KM' },
  KR: { code: 'KRW', symbol: '₩',      locale: 'ko-KR' },
  KW: { code: 'KWD', symbol: 'د.ك',   locale: 'ar-KW' },
  KZ: { code: 'KZT', symbol: '₸',      locale: 'kk-KZ' },
  LA: { code: 'LAK', symbol: '₭',      locale: 'lo-LA' },
  LB: { code: 'LBP', symbol: '£',      locale: 'ar-LB' },
  LI: { code: 'CHF', symbol: 'Fr',    locale: 'de-LI' },
  LK: { code: 'LKR', symbol: '₨',      locale: 'si-LK' },
  LR: { code: 'LRD', symbol: '$',      locale: 'en-LR' },
  LS: { code: 'LSL', symbol: 'L',      locale: 'en-LS' },
  LT: { code: 'EUR', symbol: '€',      locale: 'lt-LT' },
  LU: { code: 'EUR', symbol: '€',      locale: 'fr-LU' },
  LV: { code: 'EUR', symbol: '€',      locale: 'lv-LV' },
  LY: { code: 'LYD', symbol: 'ل.د',   locale: 'ar-LY' },
  MA: { code: 'MAD', symbol: 'DH',    locale: 'fr-MA' },
  MC: { code: 'EUR', symbol: '€',      locale: 'fr-MC' },
  MD: { code: 'MDL', symbol: 'L',      locale: 'ro-MD' },
  ME: { code: 'EUR', symbol: '€',      locale: 'sr-ME' },
  MG: { code: 'MGA', symbol: 'Ar',    locale: 'fr-MG' },
  MK: { code: 'MKD', symbol: 'ден',   locale: 'mk-MK' },
  ML: { code: 'XOF', symbol: 'F CFA',  locale: 'fr-ML' },
  MM: { code: 'MMK', symbol: 'K',      locale: 'my-MM' },
  MN: { code: 'MNT', symbol: '₮',      locale: 'mn-MN' },
  MR: { code: 'MRU', symbol: 'UM',    locale: 'ar-MR' },
  MT: { code: 'EUR', symbol: '€',      locale: 'mt-MT' },
  MU: { code: 'MUR', symbol: '₨',      locale: 'fr-MU' },
  MV: { code: 'MVR', symbol: 'Rf',    locale: 'dv-MV' },
  MW: { code: 'MWK', symbol: 'MK',    locale: 'en-MW' },
  MX: { code: 'MXN', symbol: '$',      locale: 'es-MX' },
  MY: { code: 'MYR', symbol: 'RM',    locale: 'ms-MY' },
  MZ: { code: 'MZN', symbol: 'MT',    locale: 'pt-MZ' },
  NA: { code: 'NAD', symbol: '$',      locale: 'en-NA' },
  NE: { code: 'XOF', symbol: 'F CFA',  locale: 'fr-NE' },
  NG: { code: 'NGN', symbol: '₦',      locale: 'en-NG' },
  NI: { code: 'NIO', symbol: 'C$',    locale: 'es-NI' },
  NL: { code: 'EUR', symbol: '€',      locale: 'nl-NL' },
  NO: { code: 'NOK', symbol: 'kr',    locale: 'nb-NO' },
  NP: { code: 'NPR', symbol: '₨',      locale: 'ne-NP' },
  NZ: { code: 'NZD', symbol: '$',      locale: 'en-NZ' },
  OM: { code: 'OMR', symbol: '﷼',      locale: 'ar-OM' },
  PA: { code: 'PAB', symbol: 'B/.',    locale: 'es-PA' },
  PE: { code: 'PEN', symbol: 'S/',    locale: 'es-PE' },
  PG: { code: 'PGK', symbol: 'K',      locale: 'en-PG' },
  PH: { code: 'PHP', symbol: '₱',      locale: 'en-PH' },
  PK: { code: 'PKR', symbol: '₨',      locale: 'ur-PK' },
  PL: { code: 'PLN', symbol: 'zł',    locale: 'pl-PL' },
  PT: { code: 'EUR', symbol: '€',      locale: 'pt-PT' },
  PY: { code: 'PYG', symbol: '₲',      locale: 'es-PY' },
  QA: { code: 'QAR', symbol: 'ر.ق',   locale: 'ar-QA' },
  RO: { code: 'RON', symbol: 'lei',   locale: 'ro-RO' },
  RS: { code: 'RSD', symbol: 'дин.',  locale: 'sr-RS' },
  RU: { code: 'RUB', symbol: '₽',      locale: 'ru-RU' },
  RW: { code: 'RWF', symbol: 'Fr',    locale: 'fr-RW' },
  SA: { code: 'SAR', symbol: '﷼',      locale: 'ar-SA' },
  SB: { code: 'SBD', symbol: '$',      locale: 'en-SB' },
  SC: { code: 'SCR', symbol: '₨',      locale: 'fr-SC' },
  SD: { code: 'SDG', symbol: 'ج.س.',  locale: 'ar-SD' },
  SE: { code: 'SEK', symbol: 'kr',    locale: 'sv-SE' },
  SG: { code: 'SGD', symbol: '$',      locale: 'en-SG' },
  SI: { code: 'EUR', symbol: '€',      locale: 'sl-SI' },
  SK: { code: 'EUR', symbol: '€',      locale: 'sk-SK' },
  SL: { code: 'SLL', symbol: 'Le',    locale: 'en-SL' },
  SM: { code: 'EUR', symbol: '€',      locale: 'it-SM' },
  SN: { code: 'XOF', symbol: 'F CFA',  locale: 'fr-SN' },
  SO: { code: 'SOS', symbol: 'Sh',    locale: 'so-SO' },
  SR: { code: 'SRD', symbol: '$',      locale: 'nl-SR' },
  SS: { code: 'SSP', symbol: '£',      locale: 'en-SS' },
  SY: { code: 'SYP', symbol: '£',      locale: 'ar-SY' },
  SZ: { code: 'SZL', symbol: 'L',      locale: 'en-SZ' },
  TD: { code: 'XAF', symbol: 'F CFA',  locale: 'fr-TD' },
  TG: { code: 'XOF', symbol: 'F CFA',  locale: 'fr-TG' },
  TH: { code: 'THB', symbol: '฿',      locale: 'th-TH' },
  TJ: { code: 'TJS', symbol: 'SM',    locale: 'tg-TJ' },
  TM: { code: 'TMT', symbol: 'T',      locale: 'tk-TM' },
  TN: { code: 'TND', symbol: 'DT',    locale: 'fr-TN' },
  TR: { code: 'TRY', symbol: '₺',      locale: 'tr-TR' },
  TT: { code: 'TTD', symbol: '$',      locale: 'en-TT' },
  TZ: { code: 'TZS', symbol: 'Sh',    locale: 'sw-TZ' },
  UA: { code: 'UAH', symbol: '₴',      locale: 'uk-UA' },
  UG: { code: 'UGX', symbol: 'Sh',    locale: 'sw-UG' },
  US: { code: 'USD', symbol: '$',      locale: 'en-US' },
  UY: { code: 'UYU', symbol: '$',      locale: 'es-UY' },
  UZ: { code: 'UZS', symbol: 'сўм',   locale: 'uz-UZ' },
  VA: { code: 'EUR', symbol: '€',      locale: 'it-VA' },
  VE: { code: 'VES', symbol: 'Bs.S',  locale: 'es-VE' },
  VN: { code: 'VND', symbol: '₫',      locale: 'vi-VN' },
  YE: { code: 'YER', symbol: '﷼',      locale: 'ar-YE' },
  ZA: { code: 'ZAR', symbol: 'R',      locale: 'en-ZA' },
  ZM: { code: 'ZMW', symbol: 'ZK',    locale: 'en-ZM' },
  ZW: { code: 'ZWL', symbol: '$',      locale: 'en-ZW' },
}

const TIMEZONE_DATA: Record<string, string> = {
  AD: 'Europe/Andorra',   AE: 'Asia/Dubai',        AF: 'Asia/Kabul',
  AL: 'Europe/Tirane',    AM: 'Asia/Yerevan',      AO: 'Africa/Luanda',
  AR: 'America/Argentina/Buenos_Aires',             AT: 'Europe/Vienna',
  AU: 'Australia/Sydney', AZ: 'Asia/Baku',         BA: 'Europe/Sarajevo',
  BB: 'America/Barbados', BD: 'Asia/Dhaka',        BE: 'Europe/Brussels',
  BF: 'Africa/Ouagadougou', BG: 'Europe/Sofia',    BH: 'Asia/Bahrain',
  BI: 'Africa/Bujumbura', BJ: 'Africa/Cotonou',    BN: 'Asia/Brunei',
  BO: 'America/La_Paz',   BR: 'America/Sao_Paulo', BT: 'Asia/Thimphu',
  BW: 'Africa/Gaborone',  BY: 'Europe/Minsk',      BZ: 'America/Belize',
  CA: 'America/Toronto',  CD: 'Africa/Kinshasa',   CF: 'Africa/Bangui',
  CG: 'Africa/Brazzaville', CH: 'Europe/Zurich',   CI: 'Africa/Abidjan',
  CL: 'America/Santiago', CM: 'Africa/Douala',     CN: 'Asia/Shanghai',
  CO: 'America/Bogota',   CR: 'America/Costa_Rica', CU: 'America/Havana',
  CV: 'Atlantic/Cape_Verde', CY: 'Asia/Nicosia',   CZ: 'Europe/Prague',
  DE: 'Europe/Berlin',    DJ: 'Africa/Djibouti',   DK: 'Europe/Copenhagen',
  DO: 'America/Santo_Domingo', DZ: 'Africa/Algiers', EC: 'America/Guayaquil',
  EE: 'Europe/Tallinn',   EG: 'Africa/Cairo',      ES: 'Europe/Madrid',
  ET: 'Africa/Addis_Ababa', FI: 'Europe/Helsinki', FJ: 'Pacific/Fiji',
  FR: 'Europe/Paris',     GA: 'Africa/Libreville', GB: 'Europe/London',
  GE: 'Asia/Tbilisi',     GH: 'Africa/Accra',      GM: 'Africa/Banjul',
  GN: 'Africa/Conakry',   GQ: 'Africa/Malabo',     GR: 'Europe/Athens',
  GT: 'America/Guatemala', GW: 'Africa/Bissau',    GY: 'America/Guyana',
  HN: 'America/Tegucigalpa', HR: 'Europe/Zagreb',  HT: 'America/Port-au-Prince',
  HU: 'Europe/Budapest',  ID: 'Asia/Jakarta',      IE: 'Europe/Dublin',
  IL: 'Asia/Jerusalem',   IN: 'Asia/Kolkata',      IQ: 'Asia/Baghdad',
  IR: 'Asia/Tehran',      IS: 'Atlantic/Reykjavik', IT: 'Europe/Rome',
  JM: 'America/Jamaica',  JO: 'Asia/Amman',        JP: 'Asia/Tokyo',
  KE: 'Africa/Nairobi',   KG: 'Asia/Bishkek',      KH: 'Asia/Phnom_Penh',
  KM: 'Indian/Comoro',    KR: 'Asia/Seoul',         KW: 'Asia/Kuwait',
  KZ: 'Asia/Almaty',      LA: 'Asia/Vientiane',    LB: 'Asia/Beirut',
  LI: 'Europe/Vaduz',     LK: 'Asia/Colombo',      LR: 'Africa/Monrovia',
  LS: 'Africa/Maseru',    LT: 'Europe/Vilnius',    LU: 'Europe/Luxembourg',
  LV: 'Europe/Riga',      LY: 'Africa/Tripoli',    MA: 'Africa/Casablanca',
  MC: 'Europe/Monaco',    MD: 'Europe/Chisinau',   ME: 'Europe/Podgorica',
  MG: 'Indian/Antananarivo', MK: 'Europe/Skopje',  ML: 'Africa/Bamako',
  MM: 'Asia/Rangoon',     MN: 'Asia/Ulaanbaatar',  MR: 'Africa/Nouakchott',
  MT: 'Europe/Malta',     MU: 'Indian/Mauritius',  MV: 'Indian/Maldives',
  MW: 'Africa/Blantyre',  MX: 'America/Mexico_City', MY: 'Asia/Kuala_Lumpur',
  MZ: 'Africa/Maputo',    NA: 'Africa/Windhoek',   NE: 'Africa/Niamey',
  NG: 'Africa/Lagos',     NI: 'America/Managua',   NL: 'Europe/Amsterdam',
  NO: 'Europe/Oslo',      NP: 'Asia/Kathmandu',    NZ: 'Pacific/Auckland',
  OM: 'Asia/Muscat',      PA: 'America/Panama',    PE: 'America/Lima',
  PG: 'Pacific/Port_Moresby', PH: 'Asia/Manila',   PK: 'Asia/Karachi',
  PL: 'Europe/Warsaw',    PT: 'Europe/Lisbon',     PY: 'America/Asuncion',
  QA: 'Asia/Qatar',       RO: 'Europe/Bucharest',  RS: 'Europe/Belgrade',
  RU: 'Europe/Moscow',    RW: 'Africa/Kigali',     SA: 'Asia/Riyadh',
  SB: 'Pacific/Guadalcanal', SC: 'Indian/Mahe',    SD: 'Africa/Khartoum',
  SE: 'Europe/Stockholm', SG: 'Asia/Singapore',    SI: 'Europe/Ljubljana',
  SK: 'Europe/Bratislava', SL: 'Africa/Freetown',  SN: 'Africa/Dakar',
  SO: 'Africa/Mogadishu', SR: 'America/Paramaribo', SS: 'Africa/Juba',
  SY: 'Asia/Damascus',    SZ: 'Africa/Mbabane',    TD: 'Africa/Ndjamena',
  TG: 'Africa/Lome',      TH: 'Asia/Bangkok',      TJ: 'Asia/Dushanbe',
  TM: 'Asia/Ashgabat',    TN: 'Africa/Tunis',      TR: 'Europe/Istanbul',
  TT: 'America/Port_of_Spain', TZ: 'Africa/Dar_es_Salaam',
  UA: 'Europe/Kiev',      UG: 'Africa/Kampala',    US: 'America/New_York',
  UY: 'America/Montevideo', UZ: 'Asia/Tashkent',   VE: 'America/Caracas',
  VN: 'Asia/Ho_Chi_Minh', YE: 'Asia/Aden',         ZA: 'Africa/Johannesburg',
  ZM: 'Africa/Lusaka',    ZW: 'Africa/Harare',
}

const VAT_DATA: Record<string, number[]> = {
  // EU
  FR: [20, 10, 5.5, 2.1],
  DE: [19, 7],
  IT: [22, 10, 5, 4],
  ES: [21, 10, 4],
  PT: [23, 13, 6],
  BE: [21, 12, 6],
  NL: [21, 9],
  AT: [20, 13, 10],
  FI: [25.5, 14, 10],
  SE: [25, 12, 6],
  DK: [25],
  NO: [25, 15, 12],
  PL: [23, 8, 5],
  CZ: [21, 15, 10],
  HU: [27, 18, 5],
  RO: [19, 9, 5],
  HR: [25, 13, 5],
  BG: [20, 9],
  EE: [22, 9],
  LV: [21, 12, 5],
  LT: [21, 9, 5],
  SK: [20, 10],
  SI: [22, 9.5, 5],
  GR: [24, 13, 6],
  CY: [19, 9, 5],
  MT: [18, 7, 5],
  IE: [23, 13.5, 9, 4.8],
  LU: [17, 14, 8, 3],
  CH: [8.1, 3.8, 2.6],
  GB: [20, 5],
  // OHADA
  BJ: [18],    BF: [18],    CM: [19.25], CF: [19],   CG: [18],
  CI: [18],    GA: [18],    GN: [18],    GQ: [15],   GW: [17],
  KM: [10],    CD: [16],    ML: [18],    NE: [19],   SN: [18],
  TD: [18],    TG: [18],
  // Americas
  US: [0],     CA: [5],     MX: [16],    BR: [17],
  AR: [21, 10.5], CO: [19], PE: [18],    CL: [19],
  // Asia-Pacific
  AU: [10],    NZ: [15],    JP: [10, 8], CN: [13, 9, 6],
  IN: [28, 18, 12, 5],      SG: [9],     MY: [8, 6], TH: [7],
  ID: [11],    PH: [12],    VN: [10, 5], PK: [17],   BD: [15],
  // Middle East & Africa
  SA: [15],    AE: [5],     QA: [5],     IL: [17],
  MA: [20, 14, 10, 7],      TN: [19, 13, 7], DZ: [19, 9],
  EG: [14],    ZA: [15],    NG: [7.5],   KE: [16],   GH: [12.5],
  // Europe non-EU
  RU: [20, 10], TR: [20, 10, 1], UA: [20, 7],
}

const COUNTRY_NAMES: Record<string, string> = {
  AD: 'Andorre',              AE: 'Émirats arabes unis',  AF: 'Afghanistan',
  AG: 'Antigua-et-Barbuda',  AL: 'Albanie',              AM: 'Arménie',
  AO: 'Angola',              AR: 'Argentine',            AT: 'Autriche',
  AU: 'Australie',           AZ: 'Azerbaïdjan',          BA: 'Bosnie-Herzégovine',
  BB: 'Barbade',             BD: 'Bangladesh',           BE: 'Belgique',
  BF: 'Burkina Faso',        BG: 'Bulgarie',             BH: 'Bahreïn',
  BI: 'Burundi',             BJ: 'Bénin',                BN: 'Brunéi',
  BO: 'Bolivie',             BR: 'Brésil',               BS: 'Bahamas',
  BT: 'Bhoutan',             BW: 'Botswana',             BY: 'Biélorussie',
  BZ: 'Belize',              CA: 'Canada',               CD: 'RD Congo',
  CF: 'Centrafrique',        CG: 'Congo',                CH: 'Suisse',
  CI: "Côte d'Ivoire",       CL: 'Chili',                CM: 'Cameroun',
  CN: 'Chine',               CO: 'Colombie',             CR: 'Costa Rica',
  CU: 'Cuba',                CV: 'Cap-Vert',             CY: 'Chypre',
  CZ: 'Tchéquie',            DE: 'Allemagne',            DJ: 'Djibouti',
  DK: 'Danemark',            DM: 'Dominique',            DO: 'Rép. dominicaine',
  DZ: 'Algérie',             EC: 'Équateur',             EE: 'Estonie',
  EG: 'Égypte',              ER: 'Érythrée',             ES: 'Espagne',
  ET: 'Éthiopie',            FI: 'Finlande',             FJ: 'Fidji',
  FR: 'France',              GA: 'Gabon',                GB: 'Royaume-Uni',
  GD: 'Grenade',             GE: 'Géorgie',              GH: 'Ghana',
  GM: 'Gambie',              GN: 'Guinée',               GQ: 'Guinée équatoriale',
  GR: 'Grèce',               GT: 'Guatemala',            GW: 'Guinée-Bissau',
  GY: 'Guyana',              HN: 'Honduras',             HR: 'Croatie',
  HT: 'Haïti',               HU: 'Hongrie',              ID: 'Indonésie',
  IE: 'Irlande',             IL: 'Israël',               IN: 'Inde',
  IQ: 'Irak',                IR: 'Iran',                 IS: 'Islande',
  IT: 'Italie',              JM: 'Jamaïque',             JO: 'Jordanie',
  JP: 'Japon',               KE: 'Kenya',                KG: 'Kirghizistan',
  KH: 'Cambodge',            KM: 'Comores',              KN: 'Saint-Christophe',
  KP: 'Corée du Nord',       KR: 'Corée du Sud',         KW: 'Koweït',
  KZ: 'Kazakhstan',          LA: 'Laos',                 LB: 'Liban',
  LC: 'Sainte-Lucie',        LI: 'Liechtenstein',        LK: 'Sri Lanka',
  LR: 'Libéria',             LS: 'Lesotho',              LT: 'Lituanie',
  LU: 'Luxembourg',          LV: 'Lettonie',             LY: 'Libye',
  MA: 'Maroc',               MC: 'Monaco',               MD: 'Moldavie',
  ME: 'Monténégro',          MG: 'Madagascar',           MK: 'Macédoine du Nord',
  ML: 'Mali',                MM: 'Myanmar',              MN: 'Mongolie',
  MR: 'Mauritanie',          MT: 'Malte',                MU: 'Maurice',
  MV: 'Maldives',            MW: 'Malawi',               MX: 'Mexique',
  MY: 'Malaisie',            MZ: 'Mozambique',           NA: 'Namibie',
  NE: 'Niger',               NG: 'Nigéria',              NI: 'Nicaragua',
  NL: 'Pays-Bas',            NO: 'Norvège',              NP: 'Népal',
  NR: 'Nauru',               NZ: 'Nouvelle-Zélande',     OM: 'Oman',
  PA: 'Panama',              PE: 'Pérou',                PG: 'Papouasie-N.-G.',
  PH: 'Philippines',         PK: 'Pakistan',             PL: 'Pologne',
  PT: 'Portugal',            PW: 'Palaos',               PY: 'Paraguay',
  QA: 'Qatar',               RO: 'Roumanie',             RS: 'Serbie',
  RU: 'Russie',              RW: 'Rwanda',               SA: 'Arabie saoudite',
  SB: 'Îles Salomon',        SC: 'Seychelles',           SD: 'Soudan',
  SE: 'Suède',               SG: 'Singapour',            SI: 'Slovénie',
  SK: 'Slovaquie',           SL: 'Sierra Leone',         SM: 'Saint-Marin',
  SN: 'Sénégal',             SO: 'Somalie',              SR: 'Suriname',
  SS: 'Soudan du Sud',       ST: 'Sao Tomé-et-Principe', SV: 'Salvador',
  SY: 'Syrie',               SZ: 'Eswatini',             TD: 'Tchad',
  TG: 'Togo',                TH: 'Thaïlande',            TJ: 'Tadjikistan',
  TL: 'Timor oriental',      TM: 'Turkménistan',         TN: 'Tunisie',
  TO: 'Tonga',               TR: 'Turquie',              TT: 'Trinité-et-Tobago',
  TV: 'Tuvalu',              TZ: 'Tanzanie',             UA: 'Ukraine',
  UG: 'Ouganda',             US: 'États-Unis',           UY: 'Uruguay',
  UZ: 'Ouzbékistan',         VA: 'Vatican',              VC: 'Saint-Vincent',
  VE: 'Venezuela',           VN: 'Viêt Nam',             VU: 'Vanuatu',
  WS: 'Samoa',               YE: 'Yémen',                ZA: 'Afrique du Sud',
  ZM: 'Zambie',              ZW: 'Zimbabwe',
}

// ── Exports ───────────────────────────────────────────────────────────────────

export const ALL_COUNTRIES: readonly CountryListItem[] = Object.entries(COUNTRY_NAMES)
  .map(([code, name]) => ({ code, name, flag: getFlagEmoji(code) }))
  .sort((a, b) => a.name.localeCompare(b.name, 'fr'))

export function getCountryConfig(code: string): CountryConfig {
  const upper = (code ?? 'FR').toUpperCase()
  const curr = CURRENCY_DATA[upper] ?? { code: 'USD', symbol: '$', locale: 'en-US' }

  const zone: AccountingZone = upper === 'FR' ? 'FRANCE'
    : (PAYS_OHADA as readonly string[]).includes(upper) ? 'OHADA'
    : 'IFRS'

  let currencyName = curr.code
  try {
    currencyName = new Intl.DisplayNames(['fr'], { type: 'currency' }).of(curr.code) ?? curr.code
  } catch { /* ignore */ }

  return {
    code: upper,
    name: COUNTRY_NAMES[upper] ?? upper,
    flag: getFlagEmoji(upper),
    currency: currencyName,
    currencySymbol: curr.symbol,
    currencyCode: curr.code,
    accountingZone: zone,
    accountingPlan: zone === 'FRANCE' ? 'PCG'
      : zone === 'OHADA' ? 'SYSCOHADA Révisé 2017'
      : 'IFRS',
    accountingNorms: zone === 'FRANCE' ? 'Françaises (ANC/CRC)'
      : zone === 'OHADA' ? 'OHADA (Acte Uniforme)'
      : 'IFRS (IASB)',
    vatRates: VAT_DATA[upper] ?? [0],
    locale: curr.locale,
    timezone: TIMEZONE_DATA[upper] ?? 'UTC',
  }
}
